global:
  environment: production

frontend:
  image:
    repository: defaultrgcontainer.azurecr.io/docker-mysql-nodejs-reactjs-app/frondend
    tag: latest
  service:
    type: ClusterIP
    port: 80

microservices:
  service1:
    image:
      repository: defaultrgcontainer.azurecr.io/docker-mysql-nodejs-reactjs-app/backend
      tag: latest
    service:
      type: ClusterIP
      port: 8080