# .github/workflows/deploy.yaml
name: Build and Deploy to AKS

on:
  push:
    branches: [ main ]

env:
  AZURE_REGISTRY: defaultrgcontainer.azurecr.io
  RESOURCE_GROUP: BTKONSEPT_RG
  AKS_CLUSTER: demoKub8Cluster
  HELM_RELEASE_NAME: docker-mysql-nodejs-reactjs-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.AZURE_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and push frontend
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ env.AZURE_REGISTRY }}/docker-mysql-nodejs-reactjs-app/frontend:${{ github.sha }}

    # Build and push microservices
    - name: Build and push microservices
      uses: docker/build-push-action@v4
      with: 
        context: ./backend
        push: true
        tags: ${{ env.AZURE_REGISTRY }}/docker-mysql-nodejs-reactjs-app/backend:${{ github.sha }}

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER }}

    # Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v3

    # Update Helm values with new image tags
    - name: Update Helm values
      run: |
        sed -i "s|tag:.*|tag: ${{ github.sha }}|g" ./k8s/values.yaml

    # Deploy with Helm
    - name: Deploy to AKS with Helm
      run: |
        helm upgrade --install ${{ env.HELM_RELEASE_NAME }} /k8s/chart.yaml \
          --namespace azcontainerregnamespace --create-namespace